2019-01-23 02:35:48.059  INFO 38856 --- [restartedMain] es.santalucia.api.ApiApplication         : Starting ApiApplication on MacBook-Air-77.home with PID 38856 (/Users/admin/repos/afkar/santalucia-be/build/classes/java/main started by admin in /Users/admin/repos/afkar/santalucia-be)
2019-01-23 02:35:48.079  INFO 38856 --- [restartedMain] es.santalucia.api.ApiApplication         : No active profile set, falling back to default profiles: default
2019-01-23 02:35:48.308  INFO 38856 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-01-23 02:35:48.309  INFO 38856 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-01-23 02:35:50.520  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:35:50.521  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:35:50.870  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 332ms. Found 3 repository interfaces.
2019-01-23 02:35:51.668  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:35:51.669  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:35:51.795  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:35:51.796  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:35:51.798  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:35:51.798  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 128ms. Found 0 repository interfaces.
2019-01-23 02:35:51.832  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:35:51.838  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:35:51.866  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:35:51.867  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:35:51.868  INFO 38856 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:35:51.869  INFO 38856 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 31ms. Found 0 repository interfaces.
2019-01-23 02:35:53.621  INFO 38856 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$55addd49] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:35:53.681  INFO 38856 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$d52e2a7b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:35:54.882  INFO 38856 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2019-01-23 02:35:54.954  INFO 38856 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-01-23 02:35:54.955  INFO 38856 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-01-23 02:35:54.990  INFO 38856 --- [restartedMain] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-01-23 02:35:55.220  INFO 38856 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-01-23 02:35:55.222  INFO 38856 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6912 ms
2019-01-23 02:35:56.582  INFO 38856 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:35:56.925  INFO 38856 --- [cluster-ClusterId{value='5c47c4fc00504797c8d74055', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2019-01-23 02:35:57.308  INFO 38856 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:35:57.321  INFO 38856 --- [cluster-ClusterId{value='5c47c4fd00504797c8d74056', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

2019-01-23 02:35:58.319  INFO 38856 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-23 02:35:58.699  INFO 38856 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-23 02:35:58.815  INFO 38856 --- [restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-23 02:35:59.006  INFO 38856 --- [restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-01-23 02:35:59.009  INFO 38856 --- [restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-23 02:35:59.351  INFO 38856 --- [restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-01-23 02:35:59.646  INFO 38856 --- [restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-01-23 02:36:01.036 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:36:01.064 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:36:01.065 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:36:01.066 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:36:01.071 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table elements (
       id integer not null,
        attribute_name varchar(255),
        element_id integer,
        page_id integer,
        value varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:36:01.421 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table hibernate_sequence (
       next_val bigint
    ) engine=MyISAM
2019-01-23 02:36:01.443 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:36:01.466 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:36:01.469 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:36:01.474 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table pages (
       id integer not null,
        page_id integer,
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:36:01.500 DEBUG 38856 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table users (
       id integer not null,
        email varchar(255),
        hash varchar(255),
        username varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:36:01.525  INFO 38856 --- [restartedMain] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@1b46ace4'
2019-01-23 02:36:01.545  INFO 38856 --- [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:36:01.582  INFO 38856 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-01-23 02:36:02.706  INFO 38856 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-01-23 02:36:04.058  INFO 38856 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/manage'
2019-01-23 02:36:04.251  INFO 38856 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2019-01-23 02:36:04.260  INFO 38856 --- [restartedMain] es.santalucia.api.ApiApplication         : Started ApiApplication in 17.078 seconds (JVM running for 17.999)
2019-01-23 02:36:06.358  INFO 38856 --- [RMI TCP Connection(1)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-01-23 02:36:06.360  INFO 38856 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-01-23 02:36:06.388  INFO 38856 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 28 ms
2019-01-23 02:49:08.803  INFO 38856 --- [Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-01-23 02:49:08.808  INFO 38856 --- [Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:49:08.811  INFO 38856 --- [Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2019-01-23 02:49:08.813 DEBUG 38856 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:49:08.821 DEBUG 38856 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:49:08.826 DEBUG 38856 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:49:08.829 DEBUG 38856 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:49:08.846  INFO 38856 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-23 02:49:08.858  INFO 38856 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-23 02:49:14.927  INFO 40056 --- [restartedMain] es.santalucia.api.ApiApplication         : Starting ApiApplication on MacBook-Air-77.home with PID 40056 (/Users/admin/repos/afkar/santalucia-be/build/classes/java/main started by admin in /Users/admin/repos/afkar/santalucia-be)
2019-01-23 02:49:14.933  INFO 40056 --- [restartedMain] es.santalucia.api.ApiApplication         : No active profile set, falling back to default profiles: default
2019-01-23 02:49:15.041  INFO 40056 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-01-23 02:49:15.041  INFO 40056 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-01-23 02:49:16.546  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:49:16.547  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:49:16.879  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 318ms. Found 3 repository interfaces.
2019-01-23 02:49:17.361  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:49:17.361  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:49:17.385  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:49:17.386  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:49:17.387  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:49:17.387  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 26ms. Found 0 repository interfaces.
2019-01-23 02:49:17.395  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:49:17.396  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:49:17.406  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:49:17.407  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:49:17.408  INFO 40056 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:49:17.408  INFO 40056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 12ms. Found 0 repository interfaces.
2019-01-23 02:49:18.240  INFO 40056 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ba20c3b1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:49:18.431  INFO 40056 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$39a110e3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:49:19.004  INFO 40056 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2019-01-23 02:49:19.076  INFO 40056 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-01-23 02:49:19.077  INFO 40056 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-01-23 02:49:19.111  INFO 40056 --- [restartedMain] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-01-23 02:49:19.303  INFO 40056 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-01-23 02:49:19.303  INFO 40056 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4261 ms
2019-01-23 02:49:20.316  INFO 40056 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:49:20.564  INFO 40056 --- [cluster-ClusterId{value='5c47c8200050479c786a466c', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2019-01-23 02:49:20.776  INFO 40056 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:49:20.787  INFO 40056 --- [cluster-ClusterId{value='5c47c8200050479c786a466d', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

2019-01-23 02:49:21.738  INFO 40056 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-23 02:49:21.992  INFO 40056 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-23 02:49:22.071  INFO 40056 --- [restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-23 02:49:22.193  INFO 40056 --- [restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-01-23 02:49:22.195  INFO 40056 --- [restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-23 02:49:22.432  INFO 40056 --- [restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-01-23 02:49:22.647  INFO 40056 --- [restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-01-23 02:49:23.727 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:49:23.747 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:49:23.748 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:49:23.749 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:49:23.753 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table elements (
       id integer not null,
        attribute_name varchar(255),
        element_id integer,
        page_id integer,
        value varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:49:23.784 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table hibernate_sequence (
       next_val bigint
    ) engine=MyISAM
2019-01-23 02:49:23.805 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:49:23.821 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:49:23.823 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:49:23.825 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table pages (
       id integer not null,
        page_id integer,
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:49:23.843 DEBUG 40056 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table users (
       id integer not null,
        email varchar(255),
        hash varchar(255),
        username varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:49:23.869  INFO 40056 --- [restartedMain] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@4d6d5d8f'
2019-01-23 02:49:23.873  INFO 40056 --- [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:49:23.915  INFO 40056 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-01-23 02:49:24.929  INFO 40056 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-01-23 02:49:26.107  INFO 40056 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/manage'
2019-01-23 02:49:26.239  INFO 40056 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2019-01-23 02:49:26.243  INFO 40056 --- [restartedMain] es.santalucia.api.ApiApplication         : Started ApiApplication in 11.993 seconds (JVM running for 12.673)
2019-01-23 02:49:26.789  INFO 40056 --- [RMI TCP Connection(1)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-01-23 02:49:26.789  INFO 40056 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-01-23 02:49:26.813  INFO 40056 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 23 ms
2019-01-23 02:50:33.102  INFO 40056 --- [Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-01-23 02:50:33.109  INFO 40056 --- [Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:50:33.110  INFO 40056 --- [Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2019-01-23 02:50:33.113 DEBUG 40056 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:50:33.121 DEBUG 40056 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:50:33.123 DEBUG 40056 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:50:33.126 DEBUG 40056 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:50:33.142  INFO 40056 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-23 02:50:33.152  INFO 40056 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-23 02:50:38.070  INFO 40149 --- [restartedMain] es.santalucia.api.ApiApplication         : Starting ApiApplication on MacBook-Air-77.home with PID 40149 (/Users/admin/repos/afkar/santalucia-be/build/classes/java/main started by admin in /Users/admin/repos/afkar/santalucia-be)
2019-01-23 02:50:38.075  INFO 40149 --- [restartedMain] es.santalucia.api.ApiApplication         : No active profile set, falling back to default profiles: default
2019-01-23 02:50:38.175  INFO 40149 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-01-23 02:50:38.175  INFO 40149 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-01-23 02:50:39.686  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:50:39.686  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:50:39.949  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 254ms. Found 3 repository interfaces.
2019-01-23 02:50:40.425  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:50:40.426  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:50:40.451  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:50:40.452  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:50:40.454  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:50:40.454  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 28ms. Found 0 repository interfaces.
2019-01-23 02:50:40.461  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:50:40.462  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:50:40.469  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:50:40.471  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:50:40.472  INFO 40149 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:50:40.473  INFO 40149 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11ms. Found 0 repository interfaces.
2019-01-23 02:50:41.308  INFO 40149 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$300fb5db] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:50:41.397  INFO 40149 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$af90030d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:50:42.160  INFO 40149 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2019-01-23 02:50:42.238  INFO 40149 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-01-23 02:50:42.240  INFO 40149 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-01-23 02:50:42.264  INFO 40149 --- [restartedMain] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-01-23 02:50:42.519  INFO 40149 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-01-23 02:50:42.520  INFO 40149 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4344 ms
2019-01-23 02:50:43.871  INFO 40149 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:50:44.222  INFO 40149 --- [cluster-ClusterId{value='5c47c8730050479cd519a7fc', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2019-01-23 02:50:44.531  INFO 40149 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:50:44.540  INFO 40149 --- [cluster-ClusterId{value='5c47c8740050479cd519a7fd', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

2019-01-23 02:50:45.360  INFO 40149 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-23 02:50:45.615  INFO 40149 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-23 02:50:45.694  INFO 40149 --- [restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-23 02:50:45.818  INFO 40149 --- [restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-01-23 02:50:45.821  INFO 40149 --- [restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-23 02:50:46.083  INFO 40149 --- [restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-01-23 02:50:46.395  INFO 40149 --- [restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-01-23 02:50:48.060 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:50:48.096 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:50:48.097 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:50:48.100 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:50:48.105 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table elements (
       id integer not null,
        attribute_name varchar(255),
        element_id integer,
        page_id integer,
        value varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:50:48.161 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table hibernate_sequence (
       next_val bigint
    ) engine=MyISAM
2019-01-23 02:50:48.201 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:50:48.205 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:50:48.206 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:50:48.208 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table pages (
       id integer not null,
        page_id integer,
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:50:48.229 DEBUG 40149 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table users (
       id integer not null,
        email varchar(255),
        hash varchar(255),
        username varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:50:48.495  INFO 40149 --- [restartedMain] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@3bec9965'
2019-01-23 02:50:48.500  INFO 40149 --- [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:50:48.541  INFO 40149 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-01-23 02:50:49.754  INFO 40149 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-01-23 02:50:50.070  WARN 40149 --- [restartedMain] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2019-01-23 02:50:51.095  INFO 40149 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/manage'
2019-01-23 02:50:51.282  INFO 40149 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2019-01-23 02:50:51.287  INFO 40149 --- [restartedMain] es.santalucia.api.ApiApplication         : Started ApiApplication in 13.866 seconds (JVM running for 14.599)
2019-01-23 02:50:51.715  INFO 40149 --- [RMI TCP Connection(1)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-01-23 02:50:51.715  INFO 40149 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-01-23 02:50:51.792  INFO 40149 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 76 ms
2019-01-23 02:56:00.564  INFO 40149 --- [Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-01-23 02:56:00.570  INFO 40149 --- [Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:56:00.574  INFO 40149 --- [Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2019-01-23 02:56:00.576 DEBUG 40149 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:56:00.586 DEBUG 40149 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:56:00.588 DEBUG 40149 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:56:00.590 DEBUG 40149 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:56:00.606  INFO 40149 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-23 02:56:00.617  INFO 40149 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-23 02:56:08.854  INFO 40569 --- [restartedMain] es.santalucia.api.ApiApplication         : Starting ApiApplication on MacBook-Air-77.home with PID 40569 (/Users/admin/repos/afkar/santalucia-be/build/classes/java/main started by admin in /Users/admin/repos/afkar/santalucia-be)
2019-01-23 02:56:08.864  INFO 40569 --- [restartedMain] es.santalucia.api.ApiApplication         : No active profile set, falling back to default profiles: default
2019-01-23 02:56:09.028  INFO 40569 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-01-23 02:56:09.029  INFO 40569 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-01-23 02:56:11.160  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:56:11.161  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:56:11.444  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 270ms. Found 3 repository interfaces.
2019-01-23 02:56:12.172  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:56:12.172  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:56:12.206  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:56:12.208  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:56:12.211  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:56:12.211  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 38ms. Found 0 repository interfaces.
2019-01-23 02:56:12.231  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:56:12.231  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:56:12.344  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:56:12.348  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:56:12.349  INFO 40569 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:56:12.349  INFO 40569 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 118ms. Found 0 repository interfaces.
2019-01-23 02:56:13.691  INFO 40569 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$5b0fb8db] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:56:13.881  INFO 40569 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$da90060d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:56:14.486  INFO 40569 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2019-01-23 02:56:14.546  INFO 40569 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-01-23 02:56:14.547  INFO 40569 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-01-23 02:56:14.565  INFO 40569 --- [restartedMain] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-01-23 02:56:14.740  INFO 40569 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-01-23 02:56:14.741  INFO 40569 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5712 ms
2019-01-23 02:56:15.847  INFO 40569 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:56:16.147  INFO 40569 --- [cluster-ClusterId{value='5c47c9bf0050479e79f8edc4', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2019-01-23 02:56:16.453  INFO 40569 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:56:16.465  INFO 40569 --- [cluster-ClusterId{value='5c47c9c00050479e79f8edc5', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

2019-01-23 02:56:17.331  INFO 40569 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-23 02:56:17.578  INFO 40569 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-23 02:56:17.657  INFO 40569 --- [restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-23 02:56:17.789  INFO 40569 --- [restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-01-23 02:56:17.791  INFO 40569 --- [restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-23 02:56:18.052  INFO 40569 --- [restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-01-23 02:56:18.330  INFO 40569 --- [restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-01-23 02:56:19.750 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:56:19.790 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:56:19.792 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:56:19.793 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:56:19.801 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table elements (
       id integer not null,
        attribute_name varchar(255),
        element_id integer,
        page_id integer,
        value varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:56:19.842 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table hibernate_sequence (
       next_val bigint
    ) engine=MyISAM
2019-01-23 02:56:19.866 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:56:19.867 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:56:19.868 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:56:19.870 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table pages (
       id integer not null,
        page_id integer,
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:56:19.884 DEBUG 40569 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table users (
       id integer not null,
        email varchar(255),
        hash varchar(255),
        username varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:56:19.918  INFO 40569 --- [restartedMain] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@72198b43'
2019-01-23 02:56:19.925  INFO 40569 --- [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:56:19.958  INFO 40569 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-01-23 02:56:21.050  INFO 40569 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-01-23 02:56:21.492  WARN 40569 --- [restartedMain] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2019-01-23 02:56:23.122  INFO 40569 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/manage'
2019-01-23 02:56:23.389  INFO 40569 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2019-01-23 02:56:23.396  INFO 40569 --- [restartedMain] es.santalucia.api.ApiApplication         : Started ApiApplication in 15.367 seconds (JVM running for 16.489)
2019-01-23 02:56:26.933  INFO 40569 --- [RMI TCP Connection(1)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-01-23 02:56:26.934  INFO 40569 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-01-23 02:56:26.961  INFO 40569 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 26 ms
2019-01-23 02:56:58.861  INFO 40569 --- [Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-01-23 02:56:58.864  INFO 40569 --- [Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:56:58.865  INFO 40569 --- [Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2019-01-23 02:56:58.866 DEBUG 40569 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:56:58.873 DEBUG 40569 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:56:58.875 DEBUG 40569 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:56:58.880 DEBUG 40569 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:56:58.889  INFO 40569 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-23 02:56:58.896  INFO 40569 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-01-23 02:57:03.292  INFO 40797 --- [restartedMain] es.santalucia.api.ApiApplication         : Starting ApiApplication on MacBook-Air-77.home with PID 40797 (/Users/admin/repos/afkar/santalucia-be/build/classes/java/main started by admin in /Users/admin/repos/afkar/santalucia-be)
2019-01-23 02:57:03.300  INFO 40797 --- [restartedMain] es.santalucia.api.ApiApplication         : No active profile set, falling back to default profiles: default
2019-01-23 02:57:03.397  INFO 40797 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-01-23 02:57:03.397  INFO 40797 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-01-23 02:57:04.840  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:57:04.841  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:57:05.086  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 225ms. Found 3 repository interfaces.
2019-01-23 02:57:05.584  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:57:05.584  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:57:05.604  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:57:05.605  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:57:05.606  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data Reactive MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:57:05.606  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 22ms. Found 0 repository interfaces.
2019-01-23 02:57:05.614  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2019-01-23 02:57:05.614  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-01-23 02:57:05.628  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.ElementRepository.
2019-01-23 02:57:05.630  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.PageRepository.
2019-01-23 02:57:05.631  INFO 40797 --- [restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface es.santalucia.api.repository.UserRepository.
2019-01-23 02:57:05.631  INFO 40797 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 16ms. Found 0 repository interfaces.
2019-01-23 02:57:06.493  INFO 40797 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$4e23f942] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:57:06.554  INFO 40797 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$cda44674] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-23 02:57:07.440  INFO 40797 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2019-01-23 02:57:07.483  INFO 40797 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-01-23 02:57:07.484  INFO 40797 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-01-23 02:57:07.505  INFO 40797 --- [restartedMain] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-01-23 02:57:07.689  INFO 40797 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-01-23 02:57:07.690  INFO 40797 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4292 ms
2019-01-23 02:57:08.436  INFO 40797 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:57:08.662  INFO 40797 --- [cluster-ClusterId{value='5c47c9f40050479f5d668a56', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
	... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted

2019-01-23 02:57:08.815  INFO 40797 --- [restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-23 02:57:08.826  INFO 40797 --- [cluster-ClusterId{value='5c47c9f40050479f5d668a57', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

2019-01-23 02:57:09.600  INFO 40797 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-01-23 02:57:09.794  INFO 40797 --- [restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-01-23 02:57:09.874  INFO 40797 --- [restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-01-23 02:57:09.992  INFO 40797 --- [restartedMain] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-01-23 02:57:09.995  INFO 40797 --- [restartedMain] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-01-23 02:57:10.219  INFO 40797 --- [restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-01-23 02:57:10.426  INFO 40797 --- [restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-01-23 02:57:11.445 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 02:57:11.466 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 02:57:11.467 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 02:57:11.468 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 02:57:11.472 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table elements (
       id integer not null,
        attribute_name varchar(255),
        element_id integer,
        page_id integer,
        value varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:57:11.514 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table hibernate_sequence (
       next_val bigint
    ) engine=MyISAM
2019-01-23 02:57:11.536 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:57:11.537 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:57:11.538 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    insert into hibernate_sequence values ( 1 )
2019-01-23 02:57:11.539 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table pages (
       id integer not null,
        page_id integer,
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:57:11.563 DEBUG 40797 --- [restartedMain] org.hibernate.SQL                        : 
    
    create table users (
       id integer not null,
        email varchar(255),
        hash varchar(255),
        username varchar(255),
        primary key (id)
    ) engine=MyISAM
2019-01-23 02:57:11.588  INFO 40797 --- [restartedMain] o.h.t.schema.internal.SchemaCreatorImpl  : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@79a778d9'
2019-01-23 02:57:11.593  INFO 40797 --- [restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 02:57:11.623  INFO 40797 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-01-23 02:57:12.644  INFO 40797 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-01-23 02:57:12.920  WARN 40797 --- [restartedMain] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2019-01-23 02:57:13.765  INFO 40797 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/manage'
2019-01-23 02:57:13.896  INFO 40797 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2019-01-23 02:57:13.900  INFO 40797 --- [restartedMain] es.santalucia.api.ApiApplication         : Started ApiApplication in 11.234 seconds (JVM running for 11.861)
2019-01-23 02:57:16.855  INFO 40797 --- [RMI TCP Connection(1)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-01-23 02:57:16.855  INFO 40797 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-01-23 02:57:16.870  INFO 40797 --- [RMI TCP Connection(1)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 14 ms
2019-01-23 03:09:04.992  INFO 40797 --- [Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-01-23 03:09:04.997  INFO 40797 --- [Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-01-23 03:09:04.998  INFO 40797 --- [Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2019-01-23 03:09:05.000 DEBUG 40797 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists elements
2019-01-23 03:09:05.005 DEBUG 40797 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists hibernate_sequence
2019-01-23 03:09:05.007 DEBUG 40797 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists pages
2019-01-23 03:09:05.009 DEBUG 40797 --- [Thread-12] org.hibernate.SQL                        : 
    
    drop table if exists users
2019-01-23 03:09:05.021  INFO 40797 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-23 03:09:05.030  INFO 40797 --- [Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
